### ISSUE TITLE
Support mixed spaces/tabs indentation

### ISSUE THREAD

**Issue by NachoSoto** [behrang/YamlSwift#17]
This was originally found in `SwiftLint`: https://github.com/realm/SwiftLint/issues/308.

**Comment by behrang** [comment]
This is a bad idea. Since tabs can have different sizes in different editors, it will be ambiguous that two nodes are siblings or are parent/child. In the image in the related issue, if you change the tab size, the 3rd item will be positioned differently.

YamlSwift supports mixed spaces/tabs as long as there is no ambiguity.

**Comment by NachoSoto** [comment]
Makes sense. It would be nice to at least have better error handling so that users can be aware of what the problem is, considering how easy it is to inadvertently make this mistake.

**Comment by behrang** [comment]
I agree, but I'm afraid it would be a little hard with current implementation. I keep it in mind.
